In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("D:\\Egypt Real Estate\\dataset\\Egypt Real Estate Data.csv")

C:\Users\Mohamed2\AppData\Local\Temp\ipykernel_20188\1379770965.py:1: DtypeWarning: Columns (0: completion_status) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("D:\\Egypt Real Estate\\dataset\\Egypt Real Estate Data.csv")

In [5]:
df.head()

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,...,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,56009081.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,24500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.012018e+11,2.022126e+10,pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,56247925.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,5145000.0,...,False,NaN,492.0,Abrag Real Estate,snawara71@gmail.com,2.010012e+11,2.010072e+11,2.022126e+10,ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,56253883.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,10800000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,56250852.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,10500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.010701e+11,2.022126e+10,ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,55995764.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,19500000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007

In [6]:
df.shape

(39713, 53)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39713 entries, 0 to 39712
Data columns (total 53 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           39712 non-null  str
 1   internal_id          39712 non-null  float64
 2   category             39713 non-null  str
 3   listing_type         39713 non-null  str
 4   detail_url           39712 non-null  str
 5   property_type        39712 non-null  str
 6   offering_type        39712 non-null  str
 7   completion_status    19763 non-null  str
 8   title                39712 non-null  str
 9   price_egp            39712 non-null  float64
 10  price_period         39712 non-null  str
 11  price_currency       39713 non-null  str
 12  location_full        39712 non-null  str
 13  city                 39712 non-null  str
 14  town                 39712 non-null  str
 15  district             39366 non-null  str
 16  subdistrict          32954 non-null  str
 17  lat                  39712 non-null  float64
 18  lon                  39712 non-null  float64
 19  bedrooms             39678 non-null  str
 20  bathrooms            39683 non-null  str
 21  area_value           39712 non-null  float64
 22  area_unit            39713 non-null  str
 23  furnished            31328 non-null  str
 24  listing_level        39712 non-null  str
 25  is_premium           39713 non-null  bool
 26  is_verified          39713 non-null  bool
 27  is_featured          39713 non-null  bool
 28  is_new_construction  39713 non-null  bool
 29  is_direct_from_dev   39713 non-null  bool
 30  is_exclusive         39713 non-null  bool
 31  listed_date          39712 non-null  str
 32  images_count         39713 non-null  int64
 33  has_view_360         39713 non-null  bool
 34  video_url            202 non-null    str
 35  reference            39712 non-null  str
 36  rera                 0 non-null      float64
 37  description          39712 non-null  str
 38  amenities            39680 non-null  str
 39  payment_method       19939 non-null  str
 40  agent_id             39712 non-null  float64
 41  agent_name           39705 non-null  str
 42  agent_email          39712 non-null  str
 43  agent_is_super       39713 non-null  bool
 44  agent_languages      9172 non-null   str
 45  broker_id            39712 non-null  float64
 46  broker_name          39712 non-null  str
 47  broker_email         39510 non-null  str
 48  broker_phone         39510 non-null  float64
 49  contact_phone        39712 non-null  float64
 50  contact_whatsapp     39712 non-null  float64
 51  contact_email        39712 non-null  str
 52  scraped_at           39713 non-null  str
dtypes: bool(8), float64(11), int64(1), str(33)
memory usage: 13.9 MB

In [8]:
missing_values = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (df.isnull().sum() / len(df)) * 100
})

missing_values = (
    missing_values
    .query("missing_count > 0")
    .sort_values(by="missing_percentage", ascending=False)
)

missing_values

                   missing_count  missing_percentage
rera                       39713          100.000000
video_url                  39511           99.491350
agent_languages            30541           76.904288
completion_status          19950           50.235439
payment_method             19774           49.792259
furnished                   8385           21.113993
subdistrict                 6759           17.019616
district                     347            0.873769
broker_email                 203            0.511168
broker_phone                 203            0.511168
bedrooms                      35            0.088132
amenities                     33            0.083096
bathrooms                     30            0.075542
agent_name                     8            0.020145
internal_id                    1            0.002518
title                          1            0.002518
offering_type                  1            0.002518
property_type                  1            0.002518
detail_url                     1            0.002518
listing_id                     1            0.002518
lat                            1            0.002518
price_egp                      1            0.002518
price_period                   1            0.002518
listed_date                    1            0.002518
listing_level                  1            0.002518
lon                            1            0.002518
area_value                     1            0.002518
city                           1            0.002518
location_full                  1            0.002518
town                           1            0.002518
description                    1            0.002518
agent_email                    1            0.002518
agent_id                       1            0.002518
reference                      1            0.002518
broker_id                      1            0.002518
broker_name                    1            0.002518
contact_phone                  1            0.002518
contact_whatsapp               1            0.002518
contact_email                  1            0.002518

# completion status

In [9]:
df["completion_status"].value_counts(dropna=False)

completion_status
NaN                  19950
completed            10135
completed_primary     4304
off_plan_primary      4138
off_plan              1186
Name: count, dtype: int64

In [24]:
df["completion_status"] = (
    df["completion_status"]
    .fillna("Not Specified")
)
df["completion_status"].value_counts(dropna=False)

completion_status
Not Specified        19950
completed            10135
completed_primary     4304
off_plan_primary      4138
off_plan              1186
Name: count, dtype: int64

# payment_method

In [11]:
df["payment_method"].value_counts(dropna=False)

payment_method
NaN                    19774
cash                   12806
cash | installments     3758
installments            3375
Name: count, dtype: int64

In [12]:
df["payment_method"] = (
    df["payment_method"]
    .fillna("Not Specified")
)

In [13]:
df["payment_method"].value_counts(dropna=False)

payment_method
Not Specified          19774
cash                   12806
cash | installments     3758
installments            3375
Name: count, dtype: int64

In [14]:
df["payment_method"] = (
    df["payment_method"]
    .str.strip()
    .str.title()
)

In [15]:
df["payment_method"].value_counts(dropna=False)

payment_method
Not Specified          19774
Cash                   12806
Cash | Installments     3758
Installments            3375
Name: count, dtype: int64

# furnished

In [16]:
df["furnished"].value_counts(dropna=False)

furnished
YES       12719
NO        11033
NaN        8385
PARTLY     7576
Name: count, dtype: int64

In [17]:
furnished_mapping = {
    "YES": "Furnished",
    "NO": "Unfurnished",
    "PARTLY": "Partially Furnished"
}

df["furnished"] = df["furnished"].map(furnished_mapping)
df["furnished"].value_counts(dropna=False)

furnished
Furnished              12719
Unfurnished            11033
NaN                     8385
Partially Furnished     7576
Name: count, dtype: int64

In [18]:
df["furnished"] = (
    df["furnished"]
    .fillna("Not Specified")
)

In [19]:
df[f"furnished"].value_counts(dropna=False)

furnished
Furnished              12719
Unfurnished            11033
Not Specified           8385
Partially Furnished     7576
Name: count, dtype: int64

# subdistrict

In [25]:
df["subdistrict"] = df["subdistrict"].fillna("Not Specified")
df["subdistrict"].value_counts(dropna=False)

subdistrict
5th Settlement Compounds    11671
Not Specified                6759
El Katameya Compounds         969
Cairo Festival City           859
El Rehab Extension            624
                            ...
Fareek Awal Ali Amer St.        1
Lago Vista                      1
Al Worod District               1
Isadore                         1
Mostafa Abd Al Razek St.        1
Name: count, Length: 1135, dtype: int64

# district

In [26]:
df["district"]

0                  The 5th Settlement
1              Sheikh Zayed Compounds
2                  The 5th Settlement
3                  The 5th Settlement
4                  The 5th Settlement
                     ...
39708                        Al Rehab
39709    Cairo Alexandria Desert Road
39710    Cairo Alexandria Desert Road
39711    Cairo Alexandria Desert Road
39712              The 5th Settlement
Name: district, Length: 39713, dtype: str

In [37]:
df.loc[
    df["district"].isna(),
    ["location_full", "city", "town", "district", "subdistrict"]
].head(20)

,location_full,city,town,district,subdistrict
5,NaN,NaN,NaN,NaN,Not Specified
1215,"Noor City, Cairo",Cairo,Noor City,NaN,Not Specified
1618,"Noor City, Cairo",Cairo,Noor City,NaN,Not Specified
1879,"Mohandessin, Giza",Giza,Mohandessin,NaN,Not Specified
1959,"Noor City, Cairo",Cairo,Noor City,NaN,Not Specified
2400,"Noor City, Cairo",Cairo,Noor City,NaN,Not Specified
2402,"Noor City, Cairo",Cairo,Noor City,NaN,Not Specified
2564,"Noor City, Cairo",Cairo,Noor City,NaN,Not Specified
2610,"Noor City, Cairo",Cairo,Noor City,NaN,Not Specified
2661,"Sheikh Zayed City, Giza",Giza,Sheikh Zayed City,NaN,Not Specified
2847,"Noor City, Cairo",Cairo,Noor City,NaN,Not Specified
2870,"Ras Al Hekma, North Coast",North Coast,Ras Al Hekma,NaN,Not Specified
2872,"Sheikh Zayed City, Giza",Giza,Sheikh Zayed City,NaN,Not Specified
2876,"Al Alamein, North Coast",North Coast,Al Alamein,NaN,Not Specified
2889,"Marsa Alam, Red Sea",Red Sea,Marsa Alam,NaN,Not Specified
2890,"Marsa Alam, Red Sea",Red Sea,Marsa Alam,NaN,Not Specified
2891,"Marsa Alam, Red Sea",Red Sea,Marsa Alam,NaN,Not Specified
2905,"Sheikh Zayed City, Giza",Giza,Sheikh Zayed City,NaN,Not Specified
2906,"Sheikh Zayed City, Giza",Giza,Sheikh Zayed City,NaN,Not Specified
2907,"Sheikh Zayed City, Giza",Giza,Sheikh Zayed City,NaN,Not Specified

In [38]:
df.loc[
    df["district"].notna(),
    ["location_full", "city", "town", "district", "subdistrict"]
].head(20)

,location_full,city,town,district,subdistrict
0,"The Lakeview Boutique Villas, 5th Settlement C...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
1,"Village West, Sheikh Zayed Compounds, Sheikh Z...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Village West
2,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
3,"Lake View Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
4,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
6,"The Address, 12th District, Sheikh Zayed City,...",Giza,Sheikh Zayed City,12th District,The Address
7,"Amwaj, Sidi Abdel Rahman, North Coast",North Coast,Sidi Abdel Rahman,Amwaj,Not Specified
8,"Aeon, 6 October Compounds, 6 October City, Giza",Giza,6 October City,6 October Compounds,Aeon
9,"Swan Lake Gouna, El Gouna, Hurghada, Red Sea",Red Sea,Hurghada,El Gouna,Swan Lake Gouna
10,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
11,"Uptown Cairo Road, Al Abageyah, El Khalifa, Cairo",Cairo,El Khalifa,Al Abageyah,Uptown Cairo Road
12,"Swan Lake North Coast, Qesm Ad Dabaah, North C...",North Coast,Qesm Ad Dabaah,Swan Lake North Coast,Not Specified
13,"Swan Lake Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
14,"Palm Hills Katameya Extension, 5th Settlement ...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
15,"Swan Lake Residence, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
16,"Park Side Residence, Zed Towers, Sheikh Zayed ...",Giza,Sheikh Zayed City,Sheikh Zayed Compounds,Zed Towers
17,"Mountain View iCity, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
18,"Mountain View iCity, 5th Settlement Compounds,...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
19,"Palm Hills New Cairo, 5th Settlement Compounds...",Cairo,New Cairo City,The 5th Settlement,5th Settlement Compounds
20,"Silver Sands, Qesm Marsa Matrouh, North Coast",North Coast,Qesm Marsa Matrouh,Silver Sands,Not Specified

In [ ]:
district_nulls = df[df["district"].isna()]
district_nulls[
    ["location_full", "city", "town", "subdistrict"]
].notna().sum()

location_full    346
city             346
town             346
subdistrict      347
dtype: int64

In [57]:
district_nulls[
    ["location_full", "city", "town", "subdistrict"]
].head(20)

                  location_full         city               town    subdistrict
5                           NaN          NaN                NaN  Not Specified
1215           Noor City, Cairo        Cairo          Noor City  Not Specified
1618           Noor City, Cairo        Cairo          Noor City  Not Specified
1879          Mohandessin, Giza         Giza        Mohandessin  Not Specified
1959           Noor City, Cairo        Cairo          Noor City  Not Specified
2400           Noor City, Cairo        Cairo          Noor City  Not Specified
2402           Noor City, Cairo        Cairo          Noor City  Not Specified
2564           Noor City, Cairo        Cairo          Noor City  Not Specified
2610           Noor City, Cairo        Cairo          Noor City  Not Specified
2661    Sheikh Zayed City, Giza         Giza  Sheikh Zayed City  Not Specified
2847           Noor City, Cairo        Cairo          Noor City  Not Specified
2870  Ras Al Hekma, North Coast  North Coast       Ras Al Hekma  Not Specified
2872    Sheikh Zayed City, Giza         Giza  Sheikh Zayed City  Not Specified
2876    Al Alamein, North Coast  North Coast         Al Alamein  Not Specified
2889        Marsa Alam, Red Sea      Red Sea         Marsa Alam  Not Specified
2890        Marsa Alam, Red Sea      Red Sea         Marsa Alam  Not Specified
2891        Marsa Alam, Red Sea      Red Sea         Marsa Alam  Not Specified
2905    Sheikh Zayed City, Giza         Giza  Sheikh Zayed City  Not Specified
2906    Sheikh Zayed City, Giza         Giza  Sheikh Zayed City  Not Specified
2907    Sheikh Zayed City, Giza         Giza  Sheikh Zayed City  Not Specified

In [46]:
subdistrict_district = (
    df.dropna(subset=["district"])
      .groupby("subdistrict")["district"]
      .nunique()
      .sort_values(ascending=False)
)

subdistrict_district.head(20)

subdistrict
Not Specified                         419
1st Neighborhood                        9
Al Geish Road                           7
Port Said St.                           5
2nd Neighborhood                        4
4th Neighborhood                        3
Al Nozha St.                            3
Al Nasr Road                            3
Mostafa Kamel St.                       3
Street 13                               3
Africa   Emtedad Moustafa Al Nahas      2
Al Orouba St.                           2
El Mariouteya                           2
3rd Neighborhood                        2
Ahmed Al Zomor St.                      2
Beta Greens                             2
De Joya                                 2
Al Shabab St.                           2
Abdel Salam Aref St.                    2
Italian Square                          2
Name: district, dtype: int64

In [56]:
df["district"] = df["district"].fillna("Not Specified")
df['district'].value_counts(dropna=False)

district
The 5th Settlement        13082
Sheikh Zayed Compounds     3744
6 October Compounds        1485
North Investors Area       1180
Privado                    1007
                          ...
Zaki Ali St.                  1
El Estad                      1
Samir Zaki St.                1
Palm Springs Compound         1
Backus                        1
Name: count, Length: 520, dtype: int64