In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv("D:\\Egypt Real Estate\\dataset\\Egypt Real Estate Data.csv")

C:\Users\Mohamed2\AppData\Local\Temp\ipykernel_18748\1379770965.py:1: DtypeWarning: Columns (0: completion_status) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("D:\\Egypt Real Estate\\dataset\\Egypt Real Estate Data.csv")

In [13]:
df.head()

,listing_id,internal_id,category,listing_type,detail_url,property_type,offering_type,completion_status,title,price_egp,...,agent_is_super,agent_languages,broker_id,broker_name,broker_email,broker_phone,contact_phone,contact_whatsapp,contact_email,scraped_at
0,F7QB31CGWE509V2W7DF2GARB2C,56009081.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/duple...,Duplex,Residential for Sale,completed,Garden Villa - Lake View Boutique - Prime Loca...,24500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.012018e+11,2.022126e+10,pierre.Osama@spade-consultancy.com,2026-03-04T14:20:33.281007
1,K1JC3D6N57ED52N3VX1QQKHHXG,56247925.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,off_plan,For Sale: Finished Apartment+ ACs in Village West,5145000.0,...,False,NaN,492.0,Abrag Real Estate,snawara71@gmail.com,2.010012e+11,2.010072e+11,2.022126e+10,ranoushamer901@gmail.com,2026-03-04T14:20:33.281007
2,Q6GEB8T6PZTJGNNPWA5PX3JCWR,56253883.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,UnderMarket Price for Apt. 250 RTM PrimeLocation,10800000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007
3,PPH0852SAB266X6GSVATJP4F0M,56250852.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/apart...,Apartment,Residential for Sale,completed,lowest price 2bds fullyfurnished @ lake view,10500000.0,...,False,NaN,5758.0,Spade consultancy,mohmedg.sedik@gmail.com,1.001437e+09,2.010701e+11,2.022126e+10,ebrahim.hossam@spade-consultancy.com,2026-03-04T14:20:33.281007
4,QCSA4TNDEBBV7BNY8ANST3TB50,55995764.0,buy,property,https://www.propertyfinder.eg/en/plp/buy/villa...,Villa,Residential for Sale,completed,Exclusive Type M with Lowest Price RTM in PNC,19500000.0,...,False,English | Arabic,5279.0,Premises,mahmouddessam@hotmail.com,2.010051e+11,2.010910e+11,2.022126e+10,ashrafsobhy99@hotmail.com,2026-03-04T14:20:33.281007

In [14]:
df.shape

(39713, 53)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39713 entries, 0 to 39712
Data columns (total 53 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           39712 non-null  str
 1   internal_id          39712 non-null  float64
 2   category             39713 non-null  str
 3   listing_type         39713 non-null  str
 4   detail_url           39712 non-null  str
 5   property_type        39712 non-null  str
 6   offering_type        39712 non-null  str
 7   completion_status    19763 non-null  str
 8   title                39712 non-null  str
 9   price_egp            39712 non-null  float64
 10  price_period         39712 non-null  str
 11  price_currency       39713 non-null  str
 12  location_full        39712 non-null  str
 13  city                 39712 non-null  str
 14  town                 39712 non-null  str
 15  district             39366 non-null  str
 16  subdistrict          32954 non-null  str
 17  lat                  39712 non-null  float64
 18  lon                  39712 non-null  float64
 19  bedrooms             39678 non-null  str
 20  bathrooms            39683 non-null  str
 21  area_value           39712 non-null  float64
 22  area_unit            39713 non-null  str
 23  furnished            31328 non-null  str
 24  listing_level        39712 non-null  str
 25  is_premium           39713 non-null  bool
 26  is_verified          39713 non-null  bool
 27  is_featured          39713 non-null  bool
 28  is_new_construction  39713 non-null  bool
 29  is_direct_from_dev   39713 non-null  bool
 30  is_exclusive         39713 non-null  bool
 31  listed_date          39712 non-null  str
 32  images_count         39713 non-null  int64
 33  has_view_360         39713 non-null  bool
 34  video_url            202 non-null    str
 35  reference            39712 non-null  str
 36  rera                 0 non-null      float64
 37  description          39712 non-null  str
 38  amenities            39680 non-null  str
 39  payment_method       19939 non-null  str
 40  agent_id             39712 non-null  float64
 41  agent_name           39705 non-null  str
 42  agent_email          39712 non-null  str
 43  agent_is_super       39713 non-null  bool
 44  agent_languages      9172 non-null   str
 45  broker_id            39712 non-null  float64
 46  broker_name          39712 non-null  str
 47  broker_email         39510 non-null  str
 48  broker_phone         39510 non-null  float64
 49  contact_phone        39712 non-null  float64
 50  contact_whatsapp     39712 non-null  float64
 51  contact_email        39712 non-null  str
 52  scraped_at           39713 non-null  str
dtypes: bool(8), float64(11), int64(1), str(33)
memory usage: 13.9 MB

In [19]:
df.isnull().sum().sort_values(ascending=False)

rera                   39713
video_url              39511
agent_languages        30541
completion_status      19950
payment_method         19774
furnished               8385
subdistrict             6759
district                 347
broker_email             203
broker_phone             203
bedrooms                  35
amenities                 33
bathrooms                 30
agent_name                 8
city                       1
detail_url                 1
location_full              1
listing_id                 1
property_type              1
offering_type              1
internal_id                1
contact_email              1
agent_email                1
broker_name                1
lat                        1
price_egp                  1
price_period               1
town                       1
lon                        1
title                      1
agent_id                   1
description                1
area_value                 1
reference                  1
listed_date                1
listing_level              1
contact_phone              1
contact_whatsapp           1
broker_id                  1
category                   0
listing_type               0
price_currency             0
has_view_360               0
is_featured                0
is_new_construction        0
area_unit                  0
is_direct_from_dev         0
is_exclusive               0
images_count               0
is_premium                 0
is_verified                0
agent_is_super             0
scraped_at                 0
dtype: int64

In [20]:
missing_values = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (df.isnull().sum() / len(df)) * 100
})

missing_values = (
    missing_values
    .query("missing_count > 0")
    .sort_values(by="missing_percentage", ascending=False)
)

missing_values

                   missing_count  missing_percentage
rera                       39713          100.000000
video_url                  39511           99.491350
agent_languages            30541           76.904288
completion_status          19950           50.235439
payment_method             19774           49.792259
furnished                   8385           21.113993
subdistrict                 6759           17.019616
district                     347            0.873769
broker_email                 203            0.511168
broker_phone                 203            0.511168
bedrooms                      35            0.088132
amenities                     33            0.083096
bathrooms                     30            0.075542
agent_name                     8            0.020145
internal_id                    1            0.002518
title                          1            0.002518
offering_type                  1            0.002518
property_type                  1            0.002518
detail_url                     1            0.002518
listing_id                     1            0.002518
lat                            1            0.002518
price_egp                      1            0.002518
price_period                   1            0.002518
listed_date                    1            0.002518
listing_level                  1            0.002518
lon                            1            0.002518
area_value                     1            0.002518
city                           1            0.002518
location_full                  1            0.002518
town                           1            0.002518
description                    1            0.002518
agent_email                    1            0.002518
agent_id                       1            0.002518
reference                      1            0.002518
broker_id                      1            0.002518
broker_name                    1            0.002518
contact_phone                  1            0.002518
contact_whatsapp               1            0.002518
contact_email                  1            0.002518